general {
    # 1. This is the command that runs when the system wants to lock
    # We use "pidof" to check if it's already running so we don't spawn double locks
    lock_cmd = pidof gtklock || gtklock

    # 2. This command runs immediately before suspend (lid close)
    # We tell systemd "lock the session", which triggers the command above
    before_sleep_cmd = loginctl lock-session
}

listener {
    # Lock screen after 5 minutes (300 seconds) of inactivity
    timeout = 420
    on-timeout = loginctl lock-session
}
