[main]
# --- General Settings ---
# The GTK theme to use (must be installed on your system)
gtk-theme=Adwaita-dark
background=/usr/share/hypr/wall1.png
input-label=

# classes to apply to the window (useful for CSS styling)
style=/home/geltms/.config/gtklock/style.css

# --- Time & Date ---
# Format follows strftime (man strftime)
time-format=%I:%M %p
date-format=%A, %B %d

# --- Modules ---
# distinct modules separated by a semi-colon ';'
# Ensure you have the module .so files installed in the correct path
# modules=/usr/lib/gtklock/userinfo.so;/usr/lib/gtklock/power.so

# [userinfo]
# These settings only apply if the userinfo module is loaded above
# image-size=128
# under-clock=true
# round-image=true

# [power]
# These settings only apply if the power module is loaded above
# show-labels=true
